default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: patient_care_app

test:
  <<: *default
  database: patient_care_app

production:
  url: <%= ENV['DATABASE_URL'] %>
  variables:
    statement_timeout: <%= ENV["STATEMENT_TIMEOUT"] || "5s" %>
