default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: misty
  password: 12345
  host: localhost

development:
  <<: *default
  database: patients

test:
  <<: *default
  database: patients

production:
  <<: *default
  database: patients
  username: misty
  password: 12345
