default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: patient_care_app

test:
  <<: *default
  database: patient_care_app

production:
  <<: *default
  database: patient_care_app
